workflows:
  build-nuxt-capacitor-android:
    name: Build Nuxt + Capacitor Android
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - npm install
        - npm run generate
        - npm install -g @capacitor/cli
        - npx cap copy
        - cd android && chmod +x ./gradlew       # ✅ sửa lỗi file not found
        - cd android && ./gradlew assembleDebug  # ✅ build apk
    artifacts:
      - android/app/build/outputs/**/*.apk
