workflows:
  build-nuxt-capacitor:
    name: Build Nuxt + Capacitor Android
    max_build_duration: 30
    environment:
      node: latest
    scripts:
      - npm install
      - npm run generate
      - npm install -g @capacitor/cli
      - npx cap sync android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
