workflows:
  build-with-cordova-plugins:
    name: Build Nuxt with Capacitor + Cordova
    max_build_duration: 60
    environment:
      node: 20
      java: 17
    scripts:
      - npm install
      - npm run generate
      - npm install -g @capacitor/cli cordova
      - npx cap add android
      - npx cap sync android
      - cd android && chmod +x ./gradlew
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
