workflows:
  build-nuxt-capacitor-android:
    name: Build Nuxt + Capacitor Android
    max_build_duration: 60
    environment:
      node: latest
      java: 17
    scripts:
      - npm install
      - npm run generate
      - npm install -g @capacitor/cli
      - npx cap add android
      - npx cap copy
      - cd android
      - chmod +x ./gradlew  # ✅ Cấp quyền thực thi để tránh lỗi Permission denied
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
